filter:
    excluded_paths: [vendor/*, app/*, web/*]

before_commands:
    - composer install

tools:
    php_code_coverage:
      test_command: Console/cake test app AllTests
    php_cpd: true
    php_pdepend: true