filter:
    excluded_paths:
        - 'Vendor/*'
before_commands:
    - 'composer install'
tools:
    php_code_coverage:
        test_command: 'Console/cake test app AllTests --coverage-clover=./report'
    php_cpd:
        excluded_dirs:
            - Vendor
    php_pdepend:
        excluded_dirs:
            - Vendor
    php_loc:
        excluded_dirs:
            - Vendor