filter:
    excluded_paths:
        - 'Vendor/*'
before_commands:
    - 'composer install'
tools:
    external_code_coverage:
        timeout: 1800
    php_cpd:
        excluded_dirs:
            - Vendor
    php_pdepend:
        excluded_dirs:
            - Vendor
    php_loc:
        excluded_dirs:
            - Vendor