inherit: true

filter:
    excluded_paths: [Vendor/*]

before_commands:
    - composer install
    - mv Config/database.php.default Config/database.php

tools:
    php_code_coverage:
        test_command: Console/cake test app AllTests
        excluded_dirs: [Vendor/*]
    php_cpd:
            excluded_dirs:        [Vendor/*]
            filter:
                excluded_paths:       [Vendor/*]
    php_pdepend: true
        excluded_dirs: [Vendor/*]